[colors]
accent = "#1e66f5"
secondary = "#8839ef"
subtle = "#5c5f77"
overlay = "#7c7f93"
muted = "#9ca0b0"
surface = "#e6e9ef"
highlight = "#ccd0da"
blue = "#1e66f5"
green = "#40a02b"
yellow = "#df8e1d"
orange = "#fe640b"
red = "#d20f39"
purple = "#8839ef"
teal = "#179299"
